language: python
python:
  - "3.5"
# command to run tests
before_script:
  - pip install python-coveralls
  - pip install coverage
script:
  - coverage run -m unittest test_rpn
after_success:
  - coveralls
