language: python
python:
  - "3.5"
before_script:
  - pip install python-coveralls
  - pip install coverage
script:
  - coverage run --include rpn.py -m unittest test_rpn
after_success:
  - coveralls
